version: 2
updates:
  - package-ecosystem: docker
    directory: /
    commit-message:
      prefix: "docker"
    assignees:
    - "Harvester57"
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "actions"
    assignees:
    - "Harvester57"
    schedule:
      interval: daily
    groups:
      actions-dependencies:
        applies-to: version-updates
        patterns:
        - "*"
